
builds:
- env:
    - CGO_ENABLED=0

  ldflags:
    - -X "main.appVersion={{.Env.TRAVIS_TAG}}"

  goos:
    - darwin
    - windows
    - linux

dockers:
  -
    image_templates:
      - "ionchannel/ionize:latest"
      - "ionchannel/ionize:{{ .Env.TRAVIS_TAG }}"

    build_flag_templates:
      - "--build-arg=BUILD_PATH=/go/src/github/ion-channel/ionize"
