
builds:
- env:
    - CGO_ENABLED=0

  ldflags:
    - -X "main.appVersion={{.Env.TRAVIS_TAG}}"

  goos:
    - darwin
    - windows
    - linux

archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

dockers:
  -
    goos: linux

    goarch: amd64

    image_templates:
      - "ionchannel/ionize:latest"
      - "ionchannel/ionize:{{ .Env.TRAVIS_TAG }}"
