language: go
go:
  - 1.8
  - tip
script:
  - make unit_test
  - make build
  - make install
  - make acceptance_test
notifications:
  email: false
  slack:
    rooms:
      - ionchannel:judViUieHy4ppRX1vYhok1HK#build

before_deploy: make crosscompile

deploy:
  - provider: s3
    bucket: public.ionchannel.io
    region: us-east-1
    skip_cleanup: true
    upload-dir: files/ionize
    local_dir: deploy
    acl: public_read
    on:
      tags: true
