language: go
go:
  - 1.6
  - tip
script:
  - make unit_test
  - make build
  - make install
  - make acceptance_test
notifications:
  email: false
  slack:
    rooms:
      - ionchannel:judViUieHy4ppRX1vYhok1HK#build
