language: go

go:
  - 1.13
  - master

sudo: required

install:
  - make travis_setup

script:
  - make fmt vet lint unit_test coverage analyze install

notifications:
  email: false

deploy:
  - provider: script
    skip_cleanup: true
    script: make deploy
    on:
      go: '1.13'
      tags: true
